version: '3.1'
networks:
  shadowd_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: 172.20.0.1
# Shadownd container
services:
  db:
    image: zecure/shadowd_database:12.4
    restart: always
    volumes:
      - "${SHADOWD_DB_LOCATION}:/var/lib/postgresql/data"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"
    networks:
      - shadowd_net

  web:
    image: zecure/shadowd_ui:2
    restart: always
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
    environment:
      - "SHADOWD_DB_HOST=db"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"
    networks:
      - shadowd_net

  shadowd:
    image: zecure/shadowd:2
    restart: always
    ports:
      - 9115:9115
    links:
      - db
    depends_on:
      - db
    environment:
      - "SHADOWD_DB_HOST=db"
    env_file:
      - "${SHADOWD_ENV_DB_LOCATION}"
    networks:
      shadowd_net:
        ipv4_address: 172.20.0.21
# Wordpress container
  wpdb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress  
    networks:
      - shadowd_net

  wordpress:
    depends_on:
      - wpdb
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress  
    networks:
      - shadowd_net

  
    
  
